SELECT
    A.AUTHOR_ID,
    B.AUTHOR_NAME,
    A.CATEGORY,
    SUM(S.SALES*A.PRICE) AS TOTAL_SALES 
FROM BOOK AS A
    LEFT JOIN AUTHOR AS B
    ON A.AUTHOR_ID = B.AUTHOR_ID
    LEFT JOIN BOOK_SALES AS S
    ON A.BOOK_ID = S.BOOK_ID
WHERE LEFT(S.SALES_DATE,7) = '2022-01'
GROUP BY  
    B.AUTHOR_ID,
    B.AUTHOR_NAME,
    A.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;
