SELECT
    T.FISH_COUNT,
    T.MAX_LENGTH,
    T.FISH_TYPE
FROM (
    SELECT
        FISH_TYPE,
        COUNT(ID) AS FISH_COUNT,
        MAX(LENGTH) AS MAX_LENGTH,
        AVG(CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END) AS AVG_LENGTH --평균
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS T
WHERE T.AVG_LENGTH >= 33
ORDER BY T.FISH_TYPE;
