SELECT 
    A.FLAVOR
FROM(
    SELECT
        A.SHIPMENT_ID,
        A.FLAVOR,
        A.TOTAL_ORDER +SUM(B.TOTAL_ORDER) AS B_TOTAL

    FROM FIRST_HALF AS A
        LEFT JOIN JULY AS B
        ON A.FLAVOR = B.FLAVOR
    GROUP BY 
    A.SHIPMENT_ID,
    A.FLAVOR,
    A.TOTAL_ORDER
) AS A
    ORDER BY A.B_TOTAL DESC
    LIMIT 3;
