SELECT 
    YEAR(B.SALES_DATE) AS YEAR, 
    MONTH(B.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT B.USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT B.USER_ID) /
    (
        SELECT COUNT(USER_ID)
        FROM USER_INFO
        WHERE JOINED LIKE '2021%'
    ), 1) AS PUCHASED_RATIO
    

FROM USER_INFO AS A
    INNER JOIN ONLINE_SALE AS B
        ON A.USER_ID = B.USER_ID
            AND A.JOINED LIKE '2021%'
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE);
