SELECT
    A.CATEGORY,
    SUM(B.SALES) AS TOTAL_SALES
FROM BOOK AS A
    INNER JOIN BOOK_SALES AS B
         ON A.BOOK_ID = B.BOOK_ID
WHERE B.SALES_DATE >= '2022-01-01'
AND B.SALES_DATE < '2022-02-01'
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY ASC
;
