SELECT 
    A.AUTHOR_ID, 
    B.AUTHOR_NAME,
    A.CATEGORY,
    SUM(A.PRICE * C.SALES) AS TOTAL_SALES
FROM BOOK A
    INNER JOIN AUTHOR B
        ON A.AUTHOR_ID = B.AUTHOR_ID
    INNER JOIN BOOK_SALES C
        ON A.BOOK_ID = C.BOOK_ID
WHERE C.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC
