SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    A.GENDER AS GENDER,
    COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO AS A
    INNER JOIN ONLINE_SALE AS B
        ON A.USER_ID = B.USER_ID
            AND A.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), A.GENDER
ORDER BY YEAR, MONTH, GENDER
