-- 코드를 작성해주세요
SELECT
    COUNT(FI.ID) AS FISH_COUNT,
    FNI.FISH_NAME
FROM FISH_NAME_INFO FNI
INNER JOIN FISH_INFO FI
    ON FNI.FISH_TYPE = FI.FISH_TYPE
GROUP BY
    FNI.FISH_NAME
ORDER BY
    FISH_COUNT DESC
