-- 2022년 1월 도서 판매 데이터를 기준으로 저자 별 카테고리 별 매출액을 구해라
SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) AS SALES
FROM BOOK AS A
    INNER JOIN AUTHOR AS B
        ON A.AUTHOR_ID = B.AUTHOR_ID
    INNER JOIN BOOK_SALES AS C
        ON A.BOOK_ID = C.BOOK_ID
WHERE DATE_FORMAT(C.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC
