-- 첫번째 쿼리 -> 불필요한 서브쿼리 및 조인 사용
SELECT 
    COUNT(B.ID) AS FISH_COUNT,
    IFNULL(MAX(B.LENGTH), 10) AS MAX_LENGTH,
    B.FISH_TYPE AS FISH_TYPE
FROM
(
    SELECT 
        FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(IFNULL(LENGTH, 10)) > 33
) AS A
    INNER JOIN FISH_INFO AS B
        ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY B.FISH_TYPE
ORDER BY FISH_TYPE

-- 개선된 쿼리
SELECT 
    COUNT(ID) AS FISH_COUNT,
    IFNULL(MAX(LENGTH), 10) AS MAX_LENGTH,
    FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH, 10)) > 33
ORDER BY FISH_TYPE;
