WITH REVIEW_BEST AS (
    SELECT  
        MEMBER_ID,
        COUNT(*) AS MAX_MEMBER
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
),
MAX_REVIEW_MEM AS (
    SELECT 
        MEMBER_ID
    FROM REVIEW_BEST 
    WHERE MAX_MEMBER = (SELECT MAX(MAX_MEMBER) FROM REVIEW_BEST)
)
SELECT
    A.MEMBER_NAME,
    D.REVIEW_TEXT,
    CONVERT(VARCHAR(10), D.REVIEW_DATE, 23) AS REVIEW_DATE
FROM MEMBER_PROFILE AS A
    LEFT JOIN REVIEW_BEST AS B 
        ON A.MEMBER_ID = B.MEMBER_ID
    LEFT JOIN MAX_REVIEW_MEM AS C
        ON B.MEMBER_ID = C.MEMBER_ID
    LEFT JOIN REST_REVIEW  AS D
        ON C.MEMBER_ID = D.MEMBER_ID
WHERE C.MEMBER_ID IS NOT NULL
ORDER BY D.REVIEW_DATE ASC, D.REVIEW_TEXT ASC
-- 처음에 이렇게 풀었는데 MySql에서 CONVERT로 데이터 포맷 불가능해서 코드 수정함

CONVERT(VARCHAR(10), D.REVIEW_DATE, 23) AS REVIEW_DATE -> DATE_FORMAT(D.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
