WITH RECURSIVE CTE AS(
    SELECT 0 AS HOUR 
    
    UNION ALL
    
    SELECT 
        HOUR + 1 
    FROM CTE
    WHERE HOUR < 23 
)

SELECT
    A.HOUR,
    CASE WHEN B.COUNT IS NULL THEN 0 ELSE B.COUNT END AS COUNT
FROM CTE AS A
    LEFT JOIN 
    (
        SELECT
            HOUR(DATETIME) AS HOUR,
            COUNT(ANIMAL_ID) AS COUNT
        FROM ANIMAL_OUTS
        GROUP BY HOUR
    ) AS B
        ON A.HOUR = B.HOUR
ORDER BY A.HOUR
