WITH FEND AS (
  SELECT SUM(CODE) AS CODE
  FROM SKILLCODES
  WHERE CATEGORY = 'Front End'
)
SELECT DISTINCT 
  D.ID, 
  D.EMAIL, 
  D.FIRST_NAME, 
  D.LAST_NAME
FROM DEVELOPERS AS D
CROSS JOIN FEND
WHERE (D.SKILL_CODE & FEND.CODE) > 0
ORDER BY D.ID ASC;
