SELECT COUNT(B.FISH_TYPE)AS FISH_COUNT, B.FISH_NAME
FROM FISH_INFO AS A
    INNER JOIN FISH_NAME_INFO  AS B
        ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY B.FISH_TYPE, B.FISH_NAME
ORDER BY FISH_COUNT DESC
