SELECT
    B.AUTHOR_ID,
    B.AUTHOR_NAME,
    A.CATEGORY,
    SUM(A.PRICE * C.SALES) AS TOTAL_SALES
FROM BOOK AS A
 LEFT JOIN AUTHOR AS B
    ON A.AUTHOR_ID = B.AUTHOR_ID
 LEFT JOIN BOOK_SALES AS C
    ON A.BOOK_ID = C.BOOK_ID
WHERE SALES_DATE >= '2022-01-01'
AND SALES_DATE < '2022-02-01'
GROUP BY B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY
ORDER BY B.AUTHOR_ID ASC, A.CATEGORY DESC;
    
