SELECT 
    YEAR(B.SALES_DATE) AS YEAR,
    MONTH(B.SALES_DATE) AS MONTH,
    COUNT(DISTINCT A.USER_ID) AS 'PURCHASED_USERS',
    ROUND(COUNT(DISTINCT A.USER_ID) / 
         (
             SELECT DISTINCT
                COUNT(USER_ID)
            FROM USER_INFO  
            WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
         ), 1
    ) AS PURHASED_RATIO
FROM USER_INFO AS A
    INNER JOIN ONLINE_SALE AS B
        ON A.USER_ID = B.USER_ID
            AND A.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY YEAR, MONTH
