WITH RECURSIVE HOUR_LIST AS (
    SELECT 0 AS H
    UNION ALL
    SELECT H+1
    FROM HOUR_LIST
    WHERE H<23
)

SELECT H, COUNT(ANIMAL_ID) AS COUNT
FROM HOUR_LIST AS A
    LEFT JOIN ANIMAL_OUTS AS B
        ON A.H = HOUR(B.DATETIME)
GROUP BY H
ORDER BY H
