SELECT DISTINCT
    B.ID,
    B.EMAIL,
    B.FIRST_NAME,
    B.LAST_NAME
FROM SKILLCODES AS A
    INNER JOIN DEVELOPERS AS B
        ON A.CODE = B.SKILL_CODE & A.CODE
            AND A.CATEGORY = 'Front End'
ORDER BY B.ID
