SELECT 
    A.PRODUCT_CODE,
    SUM(A.PRICE * B.SALES_AMOUNT) AS SALE_AMT
FROM PRODUCT AS A
 INNER JOIN OFFLINE_SALE AS B
    ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY SALE_AMT DESC, A.PRODUCT_CODE ASC;
